# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 19:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=5000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_estimada', models.DateField()),
                ('presupuesto', models.IntegerField()),
                ('estado', models.CharField(choices=[('EP', 'En proceso'), ('PA', 'Pausado'), ('FI', 'Finalizado')], default='EP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('DE', 'Desarrollador'), ('LP', 'Lider de proyecto')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=5000)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estimacion', models.IntegerField()),
                ('horas_trabajadas', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('BA', 'Baja'), ('M', 'Media'), ('A', 'Alta'), ('BL', 'Bloqueante')], max_length=2, null=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En progreso'), ('FI', 'Resuelta'), ('AN', 'Anulada')], default='PE', max_length=2)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.Proyecto')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetracker.Recurso')),
            ],
        ),
    ]
